services:
  servidor-php:
    build: .
    container_name: servidor-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - TZ=Europe/Madrid
      # Reemplaza los valores de ejemplo con tus credenciales reales de MongoDB Atlas
      - MONGO_URI=mongodb+srv://<USUARIO>:<CONTRASEÑA>@<CLUSTER>.mongodb.net/?appName=<NOMBRE_APP>
